### ISSUE TITLE
Lists array error

### ISSUE THREAD

**Issue by Mythalar** [BG3-Community-Library-Team/BG3-Compatibility-Framework#75]
Hey, probably easier to have a distinct topic for each :p 

An error regarding UUIs array :

```lua
[ERROR]: [string "SubclassCompatibilityFramework/CompatibilityS..."]:15: attempt to index a nil value (local 'list')
stack traceback:
	SubclassCompatibilityFramework/CompatibilitySupport/ListsSupport/_ListCompatibility.lua:15: in global 'AddList'
	SubclassCompatibilityFramework/CompatibilitySupport/ListsSupport/_ListCompatibility.lua:31: in global 'HandleList'
	SubclassCompatibilityFramework/API/ListApi.lua:11: in field 'List'
	SubclassCompatibilityFramework/JsonLayer/ListHandler.lua:6: in global 'ParseAndSubmitLists'
	SubclassCompatibilityFramework/JsonLayer/ListHandler.lua:17: in global 'ListJsonHandler'
	SubclassCompatibilityFramework/JsonLayer/_JsonLoader.lua:18: in upvalue 'SubmitData'
	SubclassCompatibilityFramework/JsonLayer/_JsonLoader.lua:36: in function <SubclassCompatibilityFramework/JsonLayer/_JsonLoader.lua:32>
	[C++ Code]: in function 'xpcall'
	SubclassCompatibilityFramework/JsonLayer/_JsonLoader.lua:47: in global 'LoadConfigFiles'
	SubclassCompatibilityFramework/Init/_InitDefaults.lua:2: in function <SubclassCompatibilityFramework/Init/_InitDefaults.lua:1>
	[C++ Code]: in function 'xpcall'
	builtin://Libs/Event.lua:129: in method 'Throw'
	builtin://Libs/Event.lua:184: in function <builtin://Libs/Event.lua:183>
```

UUIDs does work for cantrip lists but not leveled spell lists.

Edit : Actually seems there is a issus since the insertion does not work for the Magus modded class/list, even cantrips, which is odd since it's loaded and I have no prob inserting spells in (new) modded lists such as Cleric subclasses mod...

Attached config (lists with issues are at line 1517+) and logs

[CompatibilityFrameworkConfig.json](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/files/13189407/CompatibilityFrameworkConfig.json)
[Extender Runtime 2023-10-27 13-14-31.log](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/files/13189412/Extender.Runtime.2023-10-27.13-14-31.log)

**Comment by NellsRelo** [comment]
The error is happening because it isn't able to find the List from the game using the supplied UUID, which it should if the mod is activated, that's really weird. Your JSON config appears valid, too. 

Going to try to mimic your mod set-up and see if I can dig deeper. In the meantime, I'm uploading a Debug Build that might provide more information on where things are failing There will be a _lot_ of console messages, as a heads up. Does it seem to affect mainly lists where multiple UUIDs are being being provided?

**Comment by NellsRelo** [comment]
Debug build [here](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/releases/tag/2.4.15-DBG)

**Comment by Mythalar** [comment]
Here are the logs
[Extender Runtime 2023-10-27 19-23-54.log](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/files/13192565/Extender.Runtime.2023-10-27.19-23-54.log)

**Comment by NellsRelo** [comment]
Huh, I might have uploaded the wrong build, log should have a lot more in there. So far, I've been able to find two of the lists that aren't found:

```
    {
      "Action": "Insert",
      "UUID": "c9c328b8-f066-48d9-9a2d-b6cfb62e13d8",
      "Type": "SpellList",
      "Items": [
        "Target_Command_Container",
        "Target_Sleep2e",
        "Shout_FalseLife",
        "Projectile_RayOfSickness",
        "Target_Harm2e",
        "Target_NathairsMischief",
        "Target_HoldPerson",
        "Target_WitherAndBloom",
        "Projectile_RayOfEnfeeblement",
        "Target_FeastOfAshes",
        "Target_BoneShaker",
        "Target_Slow",
        "Target_AnimateDead",
        "Target_VampiricTouch",
        "Target_VampiricTouch2e",
        "Target_Confusion",
        "Target_ResilientSphere",
        "Target_Blight",
        "Target_DeathWard",
        "Shout_ShadowOfMoil",
        "Target_DominatePerson",
        "Shout_DevouringDarkness",
        "Target_Cloudkill",
        "Projectile_NegativeEnergyFlood",
        "Target_Blister"
      ]
```

and 
```
    {
      "Action": "Insert",
      "UUID": "349c99a9-bb7b-4e3f-860b-c182a06661e7",
      "Type": "SpellList",
      "Items": [
        "Target_Command_Container",
        "Target_Sleep2e",
        "Shout_FalseLife",
        "Projectile_RayOfSickness",
        "Target_Harm2e"
      ]
    },
```

I'll upload another debug build that might help narrow the cause down in your logs

**Comment by NellsRelo** [comment]
Debug Build here: https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/releases/tag/2.4.15-DBG-B

**Comment by Mythalar** [comment]
New logs, will investigate the 2 lists!
[Extender Runtime 2023-10-27 20-45-38.log](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/files/13193170/Extender.Runtime.2023-10-27.20-45-38.log)

**Comment by Mythalar** [comment]
Ok those two are spell lists implemented by [Cleric Subclasses mod](https://www.nexusmods.com/baldursgate3/mods/432), which sure is loaded since I can choose one of the subclasses :p 
Same thing for [Magus class mod](https://www.nexusmods.com/baldursgate3/mods/422) I guess.

That would not explain why spells are not added to, IE, sorcerer cantrip list (I checked the UUID).

**Comment by NellsRelo** [comment]
Just to make sure, is your mod loading after the others you're adding to? It could be that at that step in the process the other mod's lists don't exist yet. 

The entry that prints just before the error will be the one that it can't find the list of, looks like this most recent one is:

```json
{
	"ListItems" : 
	{
		"0" : "Target_Agitate",
		"1" : "Target_DrawIre",
		"2" : "Target_Endure",
		"3" : "Projectile_FriendFetch",
		"4" : "Shout_MageArmor2e",
		"5" : "Projectile_MagicMissile2e",
		"6" : "Target_Sleep2e",
		"7" : "Target_BitingWords",
		"8" : "Zone_ColorSpray2e",
		"9" : "Target_CondordantChoir"
	},
	"ListType" : "SpellList",
	"TargetList" : "073c09e5-ccb9-4153-a210-001225a30cbb",
	"modGuid" : "143ed971-72c8-4d11-a749-2d01a9badaff"
}
```

**Comment by Mythalar** [comment]
Oh and something else, you pointed : 
```
    {
      "Action": "Insert",
      "UUID": "349c99a9-bb7b-4e3f-860b-c182a06661e7",
      "Type": "SpellList",
      "Items": [
        "Target_Command_Container",
        "Target_Sleep2e",
        "Shout_FalseLife",
        "Projectile_RayOfSickness",
        "Target_Harm2e"
      ]
    },
```
actually shows in game for the right subclass x)

**Comment by NellsRelo** [comment]
Huh, so it errors out but then still works? That's bizarre

**Comment by Mythalar** [comment]
> Just to make sure, is your mod loading after the others you're adding to? It could be that at that step in the process the other mod's lists don't exist yet.

Yes my mod loads after all those that add classes/spells etc...

**Comment by Mythalar** [comment]
Sooo I'm dumb, looks like I deleted the wrong file earlier, the one that implemented some referenced spell lists.

Now that it's back all lists seem good, so sorry for your time -_-
(but the "error that works" was a funny one)

**Comment by NellsRelo** [comment]
Happy to help 😄

**Comment by Mythalar** [comment]
Well, with me you can view and review all your code that's for sure...
