### ISSUE TITLE
Latest patches seem to break some subclasses showing up

### ISSUE THREAD

**Issue by CrimsonEdge7** [BG3-Community-Library-Team/BG3-Compatibility-Framework#80]
Since today's patches to the framework, some subclasses are being overridden in the selection menu when they were previously showing up.  They do, however, work in-game if a character already has that subclass.  This applies to several subclasses across multiple main classes.  Switching the load order causes the overridden mods to then take precedence, overriding others (for example, Shadow Sorcerer overrides Aberrant Mind when loaded last, but Aberrant Mind shows up if loaded after Shadow Sorcerer).

Examples:

Before (version 2.5.5)
![image](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/assets/144570554/256ddc99-e7ee-4d05-be88-1b6c527a8153)

After (version 2.6.1.1)
![image](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/assets/144570554/a6a18ab7-1a0f-4cf2-aa47-b0f1059914e4)

Load order:
![image](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/assets/144570554/d8b86966-1e03-40ad-971b-b615490fde2b)

**Comment by NellsRelo** [comment]
This is an issue the authors of these mods will need to fix, unfortunately. This issue affects mods that are called CF's API on SessionLoaded. They'll need to modify it to occur on StatsLoaded.

**Comment by CrimsonEdge7** [comment]
Would this fix potentially be simple enough to include in your "Compatibility Framework Legacy Support Patches" mod(s)?  I only ask because it's possible some of these mods never update.  Alternatively, would it be something I could easily edit on my side to make them compatible again?

**Comment by NellsRelo** [comment]
It'd be overall simple to set up, and I plan to get a few set up over the weekend, prioritizing the no-longer active mod authors. I've announced in a few locations the breaking change, but it's not something I have the bandwidth to tackle completely. It would be easy to set up a patch mod though - see the Legacy Patches folder in this repo for an example of what it would look like

**Comment by RandoRuda** [comment]
> Would this fix potentially be simple enough to include in your "Compatibility Framework Legacy Support Patches" mod(s)? I only ask because it's possible some of these mods never update. Alternatively, would it be something I could easily edit on my side to make them compatible again?

A few Legacy Patches have been created. It's worth noting that the flagged Warlock patches have been made.
https://www.nexusmods.com/baldursgate3/mods/4131/

**Comment by CrimsonEdge7** [comment]
Awesome!  I'm still seeing a few subclasses experiencing the issue, but I think either you or the modders put out patches for most of them so far.  Looks like out of the ones I have installed, Sun Soul (Yoshi) and Mercy (PlatypusVenom) monks, Bladesinger (DiZ) and War Magic (fierrof) wizards, Divine Soul (Dr. Ariella Nightshade, but made compatible by Dragonify03 on Nexus) sorcerer, Rune Knight (Nevak) and Samurai (Bonnaventura) fighters, Circle of Dreams (Yoshi) druid, Glamour (Bones687) bard, and Hexblade (Feriat) warlock have not yet received a patch from the creator or you.  Whether all of them actually need a patch I don't know, but that's what I'm seeing when looking at my mod list and recent updates from the creators.
