### ISSUE TITLE
[BUG] Selector Duplication Issue

### ISSUE THREAD

**Issue by RandoRuda** [BG3-Community-Library-Team/BG3-Compatibility-Framework#95]
There seems to be an issue when Inserting new selectors and the `Function` type already exist at that progression - the API appears to be changing all instances of that `function` to the details added, instead of adding a new one.

This was first noticed when attempting to add a `SelectSpells` for a Warlock subclass level 4 where they gain cantrips and spells.

Further testing is still required.

**Comment by NellsRelo** [comment]
Fixed in 2.6.3.5
