### ISSUE TITLE
Errors on load with v2.6.3.5 possibly related to the Lists Module

### ISSUE THREAD

**Issue by fparent** [BG3-Community-Library-Team/BG3-Compatibility-Framework#96]
hey there, this morning I was testing with v2.6.3.5 and I'm now getting some errors on load:

> bg3se::lua::State::LoadScript(): Failed to execute script: [string "SubclassCompatibilityFramework/Init/_InitGlob..."]:)
stack traceback:
        SubclassCompatibilityFramework/Init/_InitGlobals.lua:15: in main chunk
        [C++ Code]: in field 'Include'
        builtin://BuiltinLibrary.lua:61: in field 'Require'
        SubclassCompatibilityFramework/BootstrapClient.lua:1: in main chunk
        [C++ Code]: in field 'Include'
        builtin://BuiltinLibrary.lua:98: in function <builtin://BuiltinLibrary.lua:70>
bg3se::lua::State::LoadScript(): Failed to execute script: [string "SubclassCompatibilityFramework/BootstrapClien..."]:)
stack traceback:
        SubclassCompatibilityFramework/BootstrapClient.lua:7: in main chunk
        [C++ Code]: in field 'Include'
        builtin://BuiltinLibrary.lua:98: in function <builtin://BuiltinLibrary.lua:70>
Error while dispatching event StatsLoaded:      [string "SubclassCompatibilityFramework/API/ListApi.lu..."]:4: attempt )
stack traceback:
        SubclassCompatibilityFramework/API/ListApi.lua:4: in field 'InsertToList'
        Valkrana's Spellbook/Valkrana_CompatibilityFramework.lua:277: in function <Valkrana's Spellbook/Valkrana_Compat>
        [C++ Code]: in function 'xpcall'
        builtin://Libs/Event.lua:129: in method 'Throw'
        builtin://Libs/Event.lua:184: in function <builtin://Libs/Event.lua:183>

note: the issue was reported on Nexus from someone saying "Valkrana's Spellbook" weren't showing anymore with my mod. 

I'm testing with these mods and SE v11:
- 5eSpells (1.1.3.5)
- Valkrana's Spellbook (1.27.38.0)
- WarlockUndead (2.8.0)
- CompatibilityFramework (2.6.3.5)

The error doesn't occur when using CF v2.6.3.2

Here's a gist to my CompatibilityFrameworkConfig.json in case you need: 
[https://gist.github.com/fparent/abb3d4dfbb06bc2eb5527a7e13b7a12b](https://gist.github.com/fparent/abb3d4dfbb06bc2eb5527a7e13b7a12b)

Let me know if you need more information to reproduce. I can also give you access to my mod's repo if it can help.
Thanks!

**Comment by RandoRuda** [comment]
Commenting to confirm issue in case someone else runs into it:
Required mod was missing. The Community Library is required for the compatibility framework.
