### ISSUE TITLE
CF not parsing my json file

### ISSUE THREAD

**Issue by arnaudpourbaix** [BG3-Community-Library-Team/BG3-Compatibility-Framework#98]
I'm new to CF and I have followed wiki with Json file. I have created a CompatibilityFrameworkConfig.json file in my mod with this content:
```json
{
    "FileVersion": 1,
    "Progressions": [
        {
            "UUID": "dbde4d66-d3e4-4c3f-ae87-fd6e2d1cd276",
            "Strings": [
                {
                    "Action": "Remove",
                    "Type": "PassivesRemoved",
                    "Strings": [ "HumanMilitia", "HumanVersatility"]
                }
            ]
        }
    ]
}
```
My mod order:
![image](https://github.com/BG3-Community-Library-Team/BG3-Compatibility-Framework/assets/5340097/f70725b0-3e69-4684-aa9e-7fc6b272a24f)

I should not have HumanMilitia and HumanVersatility on human race, but they still appears. Does CF produces logs about what it does ? How to find them ? Or a simple log when CF is reading a mod CompatibilityFrameworkConfig file.

**Comment by arnaudpourbaix** [comment]
Update: I have looked more closely and in fact, some other changes are working fine, just not passive removal.
After digging up, I saw I had an error, it is PassivesAdded, not PassivesRemoved.

It works fine then, sorry.

**Comment by RandoRuda** [comment]
It's one a common mistake and easy to miss since you're removing an addition.
